<script>
</script>

<div class="keys">
    <div class="section">
        <p class="row q_txt">Line</p>
        <p class="row q_txt">Arc</p>
        <p class="row q_txt">Text</p>
        <p class="row q_txt">Bezier</p>
    </div>
    <div class="section">
        <p class="row q_txt">Undo</p>
        <p class="row q_txt">Delete</p>
        <p class="row q_txt">Extend</p>
        <p class="row q_txt">Fillet</p>
        <p class="row q_txt">Properties</p>
    </div>
    <div class="section">
        <p class="row q_txt">Copy</p>
        <p class="row q_txt">Import</p>
        <p class="row q_txt">Zoom</p>
    </div>
</div>

<style>
    .section {
        margin-bottom: 10px;
    }
    .row {
        line-height: 1.5;
        margin: 0px;
    }
</style>
